"""van hanh khoa hoc

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-05 10:05:46.977562
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from src.db import enable_org_rls_sql

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


NEW_TABLES = [
    "tracks",
    "cohort_tracks",
    "cohort_classes",
    "enrollments",
    "competencies",
    "track_targets",
    "competency_assessments",
    "partners",
    "partner_demand",
    "placements",
    "stipend_entries",
    "round_results",
    "composer_runs",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "partners",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("skills", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_partners_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_partners")),
        sa.UniqueConstraint("organization_id", "name", name=op.f("uq_partners_organization_id")),
    )
    op.create_index(op.f("ix_partners_organization_id"), "partners", ["organization_id"], unique=False)
    op.create_table(
        "competencies",
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("max_level", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_competencies_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"], ["programs.id"], name=op.f("fk_competencies_program_id_programs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competencies")),
        sa.UniqueConstraint("organization_id", "program_id", "code", name=op.f("uq_competencies_organization_id")),
    )
    op.create_index(op.f("ix_competencies_organization_id"), "competencies", ["organization_id"], unique=False)
    op.create_table(
        "tracks",
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_tracks_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"], ["programs.id"], name=op.f("fk_tracks_program_id_programs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracks")),
        sa.UniqueConstraint("organization_id", "program_id", "key", name=op.f("uq_tracks_organization_id")),
    )
    op.create_index(op.f("ix_tracks_organization_id"), "tracks", ["organization_id"], unique=False)
    op.create_table(
        "cohort_classes",
        sa.Column("cohort_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cohort_id"], ["cohorts.id"], name=op.f("fk_cohort_classes_cohort_id_cohorts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_cohort_classes_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cohort_classes")),
        sa.UniqueConstraint("organization_id", "cohort_id", "name", name=op.f("uq_cohort_classes_organization_id")),
    )
    op.create_index(op.f("ix_cohort_classes_organization_id"), "cohort_classes", ["organization_id"], unique=False)
    op.create_table(
        "cohort_tracks",
        sa.Column("cohort_id", sa.Uuid(), nullable=False),
        sa.Column("track_id", sa.Uuid(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cohort_id"], ["cohorts.id"], name=op.f("fk_cohort_tracks_cohort_id_cohorts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_cohort_tracks_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["track_id"], ["tracks.id"], name=op.f("fk_cohort_tracks_track_id_tracks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("cohort_id", "track_id", name=op.f("pk_cohort_tracks")),
    )
    op.create_index(op.f("ix_cohort_tracks_organization_id"), "cohort_tracks", ["organization_id"], unique=False)
    op.create_table(
        "composer_runs",
        sa.Column("cohort_id", sa.Uuid(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assignments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cohort_id"], ["cohorts.id"], name=op.f("fk_composer_runs_cohort_id_cohorts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_composer_runs_created_by_users")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_composer_runs_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_composer_runs")),
    )
    op.create_index(op.f("ix_composer_runs_cohort_id"), "composer_runs", ["cohort_id"], unique=False)
    op.create_index(op.f("ix_composer_runs_organization_id"), "composer_runs", ["organization_id"], unique=False)
    op.create_table(
        "partner_demand",
        sa.Column("cohort_id", sa.Uuid(), nullable=False),
        sa.Column("partner_id", sa.Uuid(), nullable=False),
        sa.Column("track_id", sa.Uuid(), nullable=False),
        sa.Column("slots", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cohort_id"], ["cohorts.id"], name=op.f("fk_partner_demand_cohort_id_cohorts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_partner_demand_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"], ["partners.id"], name=op.f("fk_partner_demand_partner_id_partners"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["track_id"], ["tracks.id"], name=op.f("fk_partner_demand_track_id_tracks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("cohort_id", "partner_id", "track_id", name=op.f("pk_partner_demand")),
    )
    op.create_index(op.f("ix_partner_demand_organization_id"), "partner_demand", ["organization_id"], unique=False)
    op.create_table(
        "track_targets",
        sa.Column("track_id", sa.Uuid(), nullable=False),
        sa.Column("competency_id", sa.Uuid(), nullable=False),
        sa.Column("target_level", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competencies.id"],
            name=op.f("fk_track_targets_competency_id_competencies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_track_targets_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["track_id"], ["tracks.id"], name=op.f("fk_track_targets_track_id_tracks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("track_id", "competency_id", name=op.f("pk_track_targets")),
    )
    op.create_index(op.f("ix_track_targets_organization_id"), "track_targets", ["organization_id"], unique=False)
    op.create_table(
        "enrollments",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("cohort_id", sa.Uuid(), nullable=False),
        sa.Column("class_id", sa.Uuid(), nullable=True),
        sa.Column("track_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("qualification_reason", sa.Text(), nullable=True),
        sa.Column("qualification_decided_by", sa.Uuid(), nullable=True),
        sa.Column("qualification_decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("enrolled_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('active','withdrawn','qualified','not_qualified')", name=op.f("ck_enrollments_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_enrollments_application_id_applications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["cohort_classes.id"],
            name=op.f("fk_enrollments_class_id_cohort_classes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["cohort_id"], ["cohorts.id"], name=op.f("fk_enrollments_cohort_id_cohorts"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["org_memberships.id"],
            name=op.f("fk_enrollments_membership_id_org_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_enrollments_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["qualification_decided_by"], ["users.id"], name=op.f("fk_enrollments_qualification_decided_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["track_id"], ["tracks.id"], name=op.f("fk_enrollments_track_id_tracks"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrollments")),
        sa.UniqueConstraint("organization_id", "application_id", name=op.f("uq_enrollments_organization_id")),
    )
    op.create_index("ix_enrollments_cohort", "enrollments", ["organization_id", "cohort_id", "status"], unique=False)
    op.create_index(op.f("ix_enrollments_organization_id"), "enrollments", ["organization_id"], unique=False)
    op.create_table(
        "round_results",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("round", sa.String(length=40), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("max_score", sa.Float(), nullable=False),
        sa.Column("imported_by", sa.Uuid(), nullable=True),
        sa.Column("imported_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_round_results_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["imported_by"], ["users.id"], name=op.f("fk_round_results_imported_by_users")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_round_results_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_round_results")),
        sa.UniqueConstraint(
            "organization_id", "application_id", "round", name=op.f("uq_round_results_organization_id")
        ),
    )
    op.create_index(op.f("ix_round_results_organization_id"), "round_results", ["organization_id"], unique=False)
    op.create_table(
        "competency_assessments",
        sa.Column("enrollment_id", sa.Uuid(), nullable=False),
        sa.Column("competency_id", sa.Uuid(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("assessor_membership_id", sa.Uuid(), nullable=False),
        sa.Column("assessed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessor_membership_id"],
            ["org_memberships.id"],
            name=op.f("fk_competency_assessments_assessor_membership_id_org_memberships"),
        ),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competencies.id"],
            name=op.f("fk_competency_assessments_competency_id_competencies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["enrollments.id"],
            name=op.f("fk_competency_assessments_enrollment_id_enrollments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_competency_assessments_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competency_assessments")),
    )
    op.create_index(
        "ix_comp_assess_enrollment",
        "competency_assessments",
        ["enrollment_id", "competency_id", "assessed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_competency_assessments_organization_id"), "competency_assessments", ["organization_id"], unique=False
    )
    op.create_table(
        "placements",
        sa.Column("enrollment_id", sa.Uuid(), nullable=False),
        sa.Column("partner_id", sa.Uuid(), nullable=False),
        sa.Column("mentor_membership_id", sa.Uuid(), nullable=True),
        sa.Column("project", sa.String(length=300), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["enrollments.id"],
            name=op.f("fk_placements_enrollment_id_enrollments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["mentor_membership_id"],
            ["org_memberships.id"],
            name=op.f("fk_placements_mentor_membership_id_org_memberships"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_placements_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"], ["partners.id"], name=op.f("fk_placements_partner_id_partners"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_placements")),
        sa.UniqueConstraint("organization_id", "enrollment_id", name=op.f("uq_placements_organization_id")),
    )
    op.create_index(op.f("ix_placements_organization_id"), "placements", ["organization_id"], unique=False)
    op.create_table(
        "stipend_entries",
        sa.Column("enrollment_id", sa.Uuid(), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("amount_vnd", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cost_entry_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("status IN ('eligible','paid','void')", name=op.f("ck_stipend_entries_status_valid")),
        sa.ForeignKeyConstraint(
            ["cost_entry_id"],
            ["cost_entries.id"],
            name=op.f("fk_stipend_entries_cost_entry_id_cost_entries"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["enrollments.id"],
            name=op.f("fk_stipend_entries_enrollment_id_enrollments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_stipend_entries_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stipend_entries")),
        sa.UniqueConstraint(
            "organization_id", "enrollment_id", "period", name=op.f("uq_stipend_entries_organization_id")
        ),
    )
    op.create_index(op.f("ix_stipend_entries_organization_id"), "stipend_entries", ["organization_id"], unique=False)
    for name in NEW_TABLES:
        for stmt in enable_org_rls_sql(name):
            op.execute(stmt)
    # Lịch sử đánh giá năng lực chỉ thêm, không sửa/xoá.
    op.execute(
        """
        DO $$
        BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'talenthub_app') THEN
            REVOKE UPDATE, DELETE ON competency_assessments FROM talenthub_app;
          END IF;
        END $$;
        """
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_stipend_entries_organization_id"), table_name="stipend_entries")
    op.drop_table("stipend_entries")
    op.drop_index(op.f("ix_placements_organization_id"), table_name="placements")
    op.drop_table("placements")
    op.drop_index(op.f("ix_competency_assessments_organization_id"), table_name="competency_assessments")
    op.drop_index("ix_comp_assess_enrollment", table_name="competency_assessments")
    op.drop_table("competency_assessments")
    op.drop_index(op.f("ix_round_results_organization_id"), table_name="round_results")
    op.drop_table("round_results")
    op.drop_index(op.f("ix_enrollments_organization_id"), table_name="enrollments")
    op.drop_index("ix_enrollments_cohort", table_name="enrollments")
    op.drop_table("enrollments")
    op.drop_index(op.f("ix_track_targets_organization_id"), table_name="track_targets")
    op.drop_table("track_targets")
    op.drop_index(op.f("ix_partner_demand_organization_id"), table_name="partner_demand")
    op.drop_table("partner_demand")
    op.drop_index(op.f("ix_composer_runs_organization_id"), table_name="composer_runs")
    op.drop_index(op.f("ix_composer_runs_cohort_id"), table_name="composer_runs")
    op.drop_table("composer_runs")
    op.drop_index(op.f("ix_cohort_tracks_organization_id"), table_name="cohort_tracks")
    op.drop_table("cohort_tracks")
    op.drop_index(op.f("ix_cohort_classes_organization_id"), table_name="cohort_classes")
    op.drop_table("cohort_classes")
    op.drop_index(op.f("ix_tracks_organization_id"), table_name="tracks")
    op.drop_table("tracks")
    op.drop_index(op.f("ix_competencies_organization_id"), table_name="competencies")
    op.drop_table("competencies")
    op.drop_index(op.f("ix_partners_organization_id"), table_name="partners")
    op.drop_table("partners")
    # ### end Alembic commands ###
